sudo: false
dist: xenial

language: python

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

cache:
  directories:
    - ~/.cache/pip

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6

python:
  - 3.7

before_install:
  - pip install pip setuptools --upgrade
  - pip install pip pytest --upgrade

install:
  - CC=g++-6 pip install .\[tests\] --upgrade

script:
  - (cd src && CC=gcc-6 CXX=g++-6 make -f Makefile-custom -j 4 test)
  - py.test ais test --cov=ais --cov-report term-missing
