---
title: "Untitled"
author: "Brendan Knapp"
date: "4/13/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(sf)

init <- maritime::ais_decode_list("inst/example-data/big-files/20181210.log")
df <- data.table::rbindlist(init, use.names = TRUE, fill = TRUE)
w_coords <- df[!is.na(lng_deg) & !is.na(lat_deg) & lng_deg < 179 & lng_deg > -179 & lat_deg < 89 & lng_deg > -89]


ais_sf <- w_coords %>% 
    as_tibble() %>% 
    st_as_sf(coords = c("lng_deg", "lat_deg"), crs = 4326L) %>% 
    mutate(geometry = st_make_valid(geometry))# %>%
ais_sf

eez_sf <- read_sf("~/Downloads/eez/eez.shp", as_tibble = TRUE) %>% 
    st_transform(st_crs(ais_sf)) %>% 
    mutate(geometry = st_make_valid(geometry))

eez_filled <- eez_sf %>%
    smoothr::fill_holes(threshold = Inf)

bench::mark(
    filtered <- st_filter(ais_sf, eez_filled)
)

filtered2 <- filtered %>% mutate(geometry = st_make_valid(geometry))


filtered_for_gg <- filtered2 %>% 
    group_by(mmsi) %>% 
    summarise() %>%
    st_cast("MULTIPOINT") %>% 
    st_cast("LINESTRING")

library(ggplot2)
ggplot() +
    geom_sf(data = st_crop(eez_filled, filtered2), fill = "gray") +
    geom_sf(data = st_crop(eez_sf, filtered2), fill = "lightblue") +
    geom_sf(color = "red", data = filtered_for_gg) +
    theme_minimal() +
    theme(panel.background = element_rect(fill = "blue"))
```


```{r}
print.data.table <- function(x) print(tibble::as_tibble(x))
small_df <- df[1:100]
dplyr::glimpse(small_df)

df[!is.na(imo_num)][, .N, by = .(mmsi, imo_num)][order(-N)]
```


```{r}
most_common_mmsi <- w_coords[, .N, by = mmsi][order(-N)]$mmsi[[1]]

most_common_mmsi_sf <- sf::st_as_sf(w_coords[mmsi == most_common_mmsi],
                                    coords = c("lng_deg", "lat_deg"),
                                    crs = 4326)
mapview::mapview(most_common_mmsi_sf)
```















