// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ais_version
Rcpp::List ais_version();
RcppExport SEXP _maritime_ais_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(ais_version());
    return rcpp_result_gen;
END_RCPP
}
// ais_decode_strings
Rcpp::List ais_decode_strings(const Rcpp::CharacterVector& x, const bool as_df, const bool verbose);
RcppExport SEXP _maritime_ais_decode_strings(SEXP xSEXP, SEXP as_dfSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const bool >::type as_df(as_dfSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(ais_decode_strings(x, as_df, verbose));
    return rcpp_result_gen;
END_RCPP
}
// ais_decode_file
SEXP ais_decode_file(const std::string& file_path, const bool as_df, const bool verbose);
RcppExport SEXP _maritime_ais_decode_file(SEXP file_pathSEXP, SEXP as_dfSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type file_path(file_pathSEXP);
    Rcpp::traits::input_parameter< const bool >::type as_df(as_dfSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(ais_decode_file(file_path, as_df, verbose));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ais_decode_filter_file
SEXP cpp_ais_decode_filter_file(const std::string& file_path, const int msg_type, const bool verbose);
RcppExport SEXP _maritime_cpp_ais_decode_filter_file(SEXP file_pathSEXP, SEXP msg_typeSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type file_path(file_pathSEXP);
    Rcpp::traits::input_parameter< const int >::type msg_type(msg_typeSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ais_decode_filter_file(file_path, msg_type, verbose));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ais_decode_list_file
SEXP cpp_ais_decode_list_file(const std::string& file_path, const bool verbose);
RcppExport SEXP _maritime_cpp_ais_decode_list_file(SEXP file_pathSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type file_path(file_pathSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ais_decode_list_file(file_path, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_maritime_ais_version", (DL_FUNC) &_maritime_ais_version, 0},
    {"_maritime_ais_decode_strings", (DL_FUNC) &_maritime_ais_decode_strings, 3},
    {"_maritime_ais_decode_file", (DL_FUNC) &_maritime_ais_decode_file, 3},
    {"_maritime_cpp_ais_decode_filter_file", (DL_FUNC) &_maritime_cpp_ais_decode_filter_file, 3},
    {"_maritime_cpp_ais_decode_list_file", (DL_FUNC) &_maritime_cpp_ais_decode_list_file, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_maritime(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
