# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' `libais` Version Information
#'
#' Version info for [libais](https://github.com/schwehr/libais).
#'
#' @examples
#' ais_version()
#'
#' @export
ais_version <- function() {
    .Call(`_maritime_ais_version`)
}

.ais_decode_strings <- function(x, as_df, verbose) {
    .Call(`_maritime_ais_decode_strings`, x, as_df, verbose)
}

.ais_decode_file <- function(file_path, as_df, verbose) {
    .Call(`_maritime_ais_decode_file`, file_path, as_df, verbose)
}

.ais_decode_list2 <- function(file_path, verbose) {
    .Call(`_maritime_decode_list2`, file_path, verbose)
}

