# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' `libais` Version Information
#'
#' Version info for [libais](https://github.com/schwehr/libais).
#'
#' @examples
#' ais_version()
#'
#' @export
ais_version <- function() {
    .Call(`_maritime_ais_version`)
}

.bullshit <- function(x) {
    .Call(`_maritime_bullshit`, x)
}

.ais_decode_filter_file_impl <- function(file_path, msg_type, verbose) {
    .Call(`_maritime_ais_decode_filter_file_impl`, file_path, msg_type, verbose)
}

